In [1]:
import pandas as pd
import numpy as np

import seaborn as sns

In [2]:
df = pd.DataFrame({
    'Type_of_order': ['A', 'B', 'C', 'A'],
    'Type_of_vehicle': ['car', 'truck', 'bike', 'car'],
    'City': ['New York', 'Boston', 'Chicago', 'New York']
})

In [3]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
import numpy as np

# create a 2D array representing your data with 6 categorical features
X = np.array([['Small', 'Red', 'Circle', 'First', 'Low', 'Yes'],
              ['Large', 'Blue', 'Square', 'Second', 'High', 'No'],
              ['Medium', 'Green', 'Triangle', 'Third', 'Medium', 'No']])

# specify the categories for each feature that require ordinal encoding
ordinal_categories = [['First', 'Second', 'Third'], ['Low', 'Medium', 'High'], ['Yes', 'No']]
ordinal_features = [3, 4, 5] # indices of the ordinal features in X

# create an instance of the OrdinalEncoder class
ordinal_encoder = OrdinalEncoder(categories=ordinal_categories)

# fit and transform the data using the encoder for ordinal features only
X_ordinal_encoded = ordinal_encoder.fit_transform(X[:, ordinal_features])

# create an instance of the OneHotEncoder class
onehot_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

# fit and transform the data using the encoder for one-hot encoded features only
X_onehot_encoded = onehot_encoder.fit_transform(X[:, [0, 1, 2]])

# combine the ordinal and one-hot encoded features into one dataset
X_encoded = np.concatenate((X_ordinal_encoded, X_onehot_encoded), axis=1)

# print out the encoded dataset
print(X_encoded)


[[0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 2. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [2. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1.]]


d:\ineuron\practice\ML_projects\project_tasks\deliverytime_ML_model\Venv\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [4]:
df = pd.read_csv(r"D:\ineuron\practice\ML_projects\project_tasks\deliverytime_ML_model\data\processed\final_processed_data.csv")

In [5]:
df.head()

Delivery_person_Age  Delivery_person_Ratings  Restaurant_latitude  \
0                 36.0                      4.2            30.327968   
1                 21.0                      4.7            10.003064   
2                 34.0                      4.3            30.899584   
3                 24.0                      4.7            26.463504   
4                 29.0                      4.5            19.176269   

   Restaurant_longitude  Delivery_location_latitude  \
0             78.046106                   30.397968   
1             76.307589                   10.043064   
2             75.809346                   30.919584   
3             80.372929                   26.593504   
4             72.836721                   19.266269   

   Delivery_location_longitude Weather_conditions Road_traffic_density  \
0                    78.116106                Fog                  Jam   
1                    76.347589             Stormy                 High   
2                    75.829346         Sandstorms                  Low   
3                    80.502929                Fog                  Jam   
4                    72.926721         Sandstorms                  Jam   

   Vehicle_condition Type_of_order   Type_of_vehicle  multiple_deliveries  \
0                  2         Snack        motorcycle                  3.0   
1                  1          Meal        motorcycle                  1.0   
2                  0        Buffet        motorcycle                  0.0   
3                  1         Snack           scooter                  1.0   
4                  2        Buffet  electric_scooter                  1.0   

  Festival           City  Time_taken (min)  Time_Orderd_hour  \
0       No  Metropolitian                46                21   
1       No  Metropolitian                23                14   
2       No  Metropolitian                20                 9   
3       No  Metropolitian                41                19   
4       No  Metropolitian                20                20   

   Time_Orderd_minute  Time_Order_picked_hour  Time_Order_picked_minute  
0                  55                      22                        10  
1                  55                      22                        10  
2                  20                      22                        10  
3                  50                      22                        10  
4                  25                      22                        10

In [6]:
df = pd.DataFrame({
    'Type_of_order1': ['A1', 'B1', 'C1', "NAN"],
    'Type_of_order': ['A', 'B', "Null", 'A'],
    'Type_of_vehicle': ['car', 'truck', 'bike', 'car'],
    'City': ['New York', 'Boston', 'Chicago', 'New York']
})

In [7]:
from sklearn.impute import SimpleImputer 

In [8]:
# create an instance of SimpleImputer with mean strategy
imputer = SimpleImputer(strategy="most_frequent")

# fit and transform the imputer on the data
X_imputed = imputer.fit_transform(df)

In [9]:
X_imputed

array([['A1', 'A', 'car', 'New York'],
       ['B1', 'B', 'truck', 'Boston'],
       ['C1', 'Null', 'bike', 'Chicago'],
       ['NAN', 'A', 'car', 'New York']], dtype=object)

In [10]:
# automating catagorical pipeline


class Process_cat(df):

    def __init__(self,df):
        self.df = df
        self.numerical_columns = df.select_dtypes(exclude = "object")
        self.cat_for_ord_columns = df[["Weather_conditions","Road_traffic_density", "Festival"]]
        self.cat_for_ohe_columns = df[['Type_of_order', 'Type_of_vehicle', 'City']]
        self.categorical_columns =  df.select_dtypes(include = "object")


    # handel missing values

    def cat_imputer(self,df):
        df_test = self.df.copy() # create a copy of the original DataFrame
        imputer = SimpleImputer(strategy="most_frequent")
        df_test = pd.DataFrame(imputer.fit_transform(df_test), columns=df.columns)
        return df_test
    
    # ordinal encoding

    def ord_cat(self,df):
        df_test = self.df.copy()
        ord_colums = ["Weather_conditions","Road_traffic_density", "Festival"]
        wather_cat = ["Fog", "Stormy","Sandstorms","Windy", "Cloudy", "Sunny"]
        traffic_cat = ['Low','Medium','High','Jam']
        festival_cat = ['No', 'Yes']
        if [i for i in df_test.columns] == ["Weather_conditions","Road_traffic_density", "Festival"]:
            # Initialize the OrdinalEncoder
            ordinal_encode = OrdinalEncoder(categories=[wather_cat,traffic_cat,festival_cat])
            # Fit and transform the categorical variable
            df_test[ord_colums] = ordinal_encode.fit_transform(df_test[ord_colums])
        return df_test


    # one hot encoding 
    def ohe_cat(self.df):
        df_test = self.df.copy()
        onh_colums = ['Type_of_order', 'Type_of_vehicle', 'City']
        if [i for i in df_test.columns] == ['Type_of_order', 'Type_of_vehicle', 'City']:
            # pandas data frame
            df_encoded = pd.get_dummies(df_test[[i for i in onh_colums]])
        return df_encoded

    # scale values

    def scaler_cat(self,df):
        df_test = self.df.copy()
        # Initialize StandardScaler object
        scaler = StandardScaler()
        # Fit and transform the data using the scaler object
        df_test2 = scaler.fit_transform(df_test.values)
        return df_test2



SyntaxError: invalid syntax (2506274153.py, line 39)

In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.linear_model import LinearRegression

# Create sample data
x = np.array([[1], [2], [3], [4], [5]])
y = np.array([3, 5, 7, 9, 11])

# Initialize the Linear Regression model
model = LinearRegression()

# Fit the model to the data
model.fit(x, y)

# Predict values for new data points
x_new = np.array([[6], [7], [8]])
y_pred = model.predict(x_new)

# Print the predicted values
print(y_pred)

[13. 15. 17.]


In [ ]:
# Import required modules
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Define numerical pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Define categorical pipeline
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehotencoder', OneHotEncoder())
])

# Define column transformer
column_transformer = ColumnTransformer(transformers=[
    ('num', num_pipeline, numerical_columns),
    ('cat', cat_pipeline, categorical_columns)
])

# Preprocess training data using column transformer
X_train_transformed = column_transformer.fit_transform(X_train)

# Train machine learning model using preprocessed training data
model = LinearRegression()
model.fit(X_train_transformed, y_train)

# Preprocess testing data using column transformer
X_test_transformed = column_transformer.transform(X_test)

# Evaluate performance of model on preprocessed testing data
score = model.score(X_test_transformed, y_test)
print("Model accuracy:", score)
